# Generated by Django 2.0.5 on 2018-05-09 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='余额'),
        ),
        migrations.AlterField(
            model_name='card',
            name='balance_available',
            field=models.IntegerField(default=0, verbose_name='可用金额'),
        ),
        migrations.AlterField(
            model_name='card',
            name='balance_freeze',
            field=models.IntegerField(default=0, verbose_name='冻结金额'),
        ),
    ]
